### ISSUE TITLE
List all imported functions clear 

### ISSUE THREAD

**Issue by zhangchiqing** [eckyputrady/haskell-scotty-realworld-example-app#5]
This real world example app is awesome! I learned a lot from it. Thanks for sharing it.

Just a feedback:

When I was reading the code, it's difficult for me to know which module a specific function is imported from.

For example, the `createPool` here
https://github.com/eckyputrady/haskell-scotty-realworld-example-app/blob/master/src/Platform/PG.hs#L24

Is it better if the imported functions are all explicitly listed in the `import` statement?

**Comment by sshine** [comment]
> Is it better if the imported functions are all explicitly listed in the `import` statement?

Yes, it is for exactly that reason. This would be a helpful addition to the example, but perhaps we should look at making it compile with GHC 8.6.5 and LTS-14.17 first.
